---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: api-gateway-sample-app
spec:
  destination:
    name: sample-app
  sources:
    - name: api-gateway
      action: allow
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: route-root
spec:
  parentRefs:
  - name: api-gateway
    namespace: consul
  hostnames:
  - "hacky-app.wjlabs.xyz"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - kind: Service
      name: sample-app
      port: 80