apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: sample-app
spec:
  defaultSubset: 1.0.0
  subsets:
    1.0.0:
      filter: 'Service.Meta.version == 1.0.0'
    v2:
      filter: 'Service.Meta.version == v2'
    v3:
      filter: 'Service.Meta.version == v3'
    v4:
      filter: 'Service.Meta.version == v4'
