apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: sample-app
spec:
  defaultSubset: v4
  subsets:
    v1:
      filter: 'Service.Meta.version == v1'
    v2:
      filter: 'Service.Meta.version == v2'
    v3:
      filter: 'Service.Meta.version == v3'
    v4:
      filter: 'Service.Meta.version == v4'
    v5:
      filter: 'Service.Meta.version == v5'
