apiVersion: v1
kind: Service
metadata:
  name: sample-app
  labels:
    service: sample-app
    app: sample-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    service: sample-app
    app: sample-app