---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hacky-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: hacky-app
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
  destination:
    namespace: hacky-app
    server: https://kubernetes.default.svc
  sources:
  - path: deploy/apigw
    repoURL: https://github.com/WJ-Labs/hacky-app
    targetRevision: develop
  - chart: sample-app
    path: charts/sample-app
    repoURL: gs://wjlabs_helm_charts
    targetRevision: 0.1.0
    helm:
      releaseName: sample-app-0-1-0
      valueFiles: 
      - values-v1.yaml