---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hacky-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: hacky-app
spec:
  project: default
  destination:
    namespace: hacky-app
    server: https://kubernetes.default.svc
  sources:
  - path: deploy/apigw
    repoURL: https://github.com/WJ-Labs/hacky-app
    targetRevision: develop
  - chart: sample-app
    path: charts/sample-app
    repoURL: https://github.com/WJ-Labs/hacky-app
    targetRevision: develop
    helm:
      releaseName: sample-app-v1
      valuesFile: values-v1.yaml