apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: hacky-issuer
  namespace: consul
spec:
  acme:
    email: javierlgac@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: hacky-issuer-account-key
    solvers:
    - dns01:
        cloudDNS:
          project: wj-labs-407316