---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: api-gateway
  namespace: consul
  annotations:
    networking.gke.io/certmap: hacky-app-wjlabs-xyz-map
spec:
  gatewayClassName: consul
  listeners:
  - protocol: HTTPS
    port: 443
    name: https
    allowedRoutes:
      namespaces:
        from: All
  # - protocol: HTTP
  #   port: 80
  #   name: http
  #   allowedRoutes:
  #     namespaces:
  #       from: All
