---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hacky-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: hacky-app
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
  destination:
    namespace: hacky-app
    server: https://kubernetes.default.svc
  sources:
  - path: deploy/consul
    repoURL: https://github.com/WJ-Labs/hacky-app
    targetRevision: main
  - chart: sample-app
    path: charts/sample-app
    repoURL: us-west1-docker.pkg.dev/wj-labs-407316/charts
    targetRevision: v2
    helm:
      releaseName: sample-app-v2
  - chart: sample-app
    path: charts/sample-app
    repoURL: us-west1-docker.pkg.dev/wj-labs-407316/charts
    targetRevision: v3
    helm:
      releaseName: sample-app-v3
  - chart: sample-app
    path: charts/sample-app
    repoURL: us-west1-docker.pkg.dev/wj-labs-407316/charts
    targetRevision: v4
    helm:
      releaseName: sample-app-v4
  - chart: sample-app
    path: charts/sample-app
    repoURL: us-west1-docker.pkg.dev/wj-labs-407316/charts
    targetRevision: v5
    helm:
      releaseName: sample-app-v5
