{{- $serviceVersion := .Values.serviceVersion | required ".Values.serviceVersion is required" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-app.fullname" . }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sample-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sample-app.selectorLabels" . | nindent 8 }}
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/transparent-proxy: "true"
        consul.hashicorp.com/service-meta-version: "{{ $serviceVersion }}"
        consul.hashicorp.com/service-tags: "{{ $serviceVersion }}"
    spec:
      containers:
      - name: sample-app
        image:  "{{ .Values.image.repository }}:{{ $serviceVersion | default .Chart.AppVersion }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: APP_VERSION
            value: "{{ $serviceVersion }}"
