---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-app.fullname" . }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: sample-app
      app: sample-app
  template:
    metadata:
      labels:
        service: sample-app
        app: sample-app
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/transparent-proxy: "true"
        consul.hashicorp.com/service-meta-version: "{{ .Chart.AppVersion }}"
        consul.hashicorp.com/service-tags: "{{ .Chart.AppVersion }}"
    spec:
      containers:
      - name: sample-app
        image:  "{{ .Values.image.repository }}:{{ .Chart.AppVersion | default .Chart.AppVersion }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: APP_VERSION
            value: "{{ .Chart.AppVersion }}"
