name: CICD
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v*

defaults:
  run:
    shell: bash

jobs:
  docker_image:
    runs-on: [ self-hosted, Linux, X64, hacky ]
    steps:
    - name: Checkout repository
      id: checkout_repo
      uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4.0.0
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Docker Image
      id: docker_image
      run: |
        env
        if [ "$GITHUB_REF_TYPE" == "tag" ]
        then
          export VERSION="$GITHUB_REF_NAME"
        fi
        if [ "$GITHUB_EVENT_NAME" == "pull_request" ]
        then
          make build
        else
          make build
          make publish-docker-image
        fi

  helm_chart:
    runs-on: [ self-hosted, Linux, X64, hacky ]
    steps:
    - name: Checkout repository
      id: checkout_repo
      uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4.0.0
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Helm Chart
      id: helm_chart
      run: |
        env
        if [ "$GITHUB_REF_TYPE" == "tag" ]
        then
          export VERSION="$GITHUB_REF_NAME"
        fi
        if [ "$GITHUB_EVENT_NAME" == "pull_request" ]
        then
          make package-helm-chart
        else
          make package-helm-chart
          make publish-helm-chart
        fi

  terraform_cicd:
    runs-on: [ self-hosted, Linux, X64, hacky ]
    if: ${{ github.event_name != 'tag' }}
    defaults:
      run:
        working-directory: deploy
    steps:
    - name: Checkout repository
      id: checkout_repo
      uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4.0.0

    - name: Terraform setup
      id: terraform_setup
      uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 # v3.0.0
      with:
        terraform_version: "1.6.5"

    - name: Terraform init
      id: terraform_init
      run: terraform init

    - name: Terraform fmt
      id: terraform_fmt
      run: terraform fmt -diff -check

    - name: Terraform validate
      id: terraform_validate
      run: terraform validate

    - name: Terraform plan
      id: terraform_plan
      run: terraform plan

    - name: Terraform apply
      id: terraform_apply
      if: ${{ github.event_name == 'push' }}
      run: terraform apply -auto-approve -input=false
